services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=daphne

  producer:
    build:
      context: ./producer
    container_name: producer
    environment:
      - NODE_ENV=dev
    ports:
      - '8080:3000'
    depends_on:
      - redis
      - db

  consumer:
    build:
      context: ./consumer
    container_name: consumer1
    environment:
      - NODE_ENV=dev
    depends_on:
      - redis
      - db

  consumer2:
    build:
      context: ./consumer
    container_name: consumer2
    environment:
      - NODE_ENV=dev
    depends_on:
      - redis
      - db

  consumer3:
    build:
      context: ./consumer
    container_name: consumer3
    environment:
      - NODE_ENV=dev
    depends_on:
      - redis
      - db

networks:
  nestjs_network:
    driver: bridge
